namespace SwampOfSalem.Shared.Enums;

/// <summary>
/// The six personality archetypes available to alligator characters.
/// <para>
/// Personality is the primary driver of both game-simulation behaviour and
/// AI agent tone. It controls:
/// <list type="bullet">
///   <item><description>The system-prompt flavour generated by <c>PersonalityPrompts.GetSystemPrompt()</c>.</description></item>
///   <item><description>Baseline <c>ThoughtStat</c> and <c>SocialStat</c> values from <c>PersonalityConstants</c>.</description></item>
///   <item><description>Activity weights (how likely the gator is to move, talk, or host).</description></item>
///   <item><description>Walk speed, memory retention, and social-need starting value.</description></item>
///   <item><description>Relationship compatibility scores in <c>RelationshipService</c>.</description></item>
/// </list>
/// </para>
/// </summary>
public enum Personality
{
    /// <summary>Warm, upbeat, diplomatic. High social drive, low analytical depth. Emoji-heavy speech.</summary>
    Cheerful,

    /// <summary>Blunt, cynical, suspicious of everyone. High thought stat, low social warmth.</summary>
    Grumpy,

    /// <summary>Low-effort, minimal words, hates being bothered. Poor memory retention.</summary>
    Lazy,

    /// <summary>LOUD, urgent, action-oriented. Fastest walker; uses caps and exclamation marks.</summary>
    Energetic,

    /// <summary>Quiet, observant, chooses words carefully. Highest thought stat (9). Hard to read.</summary>
    Introvert,

    /// <summary>Dramatic, performative, loves attention. Highest social stat (10). Fastest to trust.</summary>
    Extrovert
}
